version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: kazakovanton/devops-for-programmers-project-74
    environment:
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_PORT: ${DATABASE_PORT}
    command: bash -c 'sleep 3 && npm test'
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_PORT: ${DATABASE_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

