version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: kazakovanton/devops-for-programmers-project-74
    environment:
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: "trust"

